version: "3.9"
services:
  api:
    depends_on:
      - db
      - mailer
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./api:/workdir
      - /workdir/node_modules
    env_file:
      - ./api/.env
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_TYPE: mongo
      DB_HOST: db
      DB_PORT: 27017
      DB_USER: admin
      DB_PASS: 123456
      DB_NAME: school
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
      MAILER_CLIENT_ID: mailer
      MAILER_CONSUMER_GROUP_ID: mailer-consumer
  mailer:
    depends_on:
      - kafka
      - kafka-zookeeper
    build:
      context: ./workers/mailer
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - 3001:3000
    volumes:
      - ./workers/mailer:/workdir
      - /workdir/node_modules
    env_file:
      - ./api/.env
    environment:
      NODE_ENV: development
      PORT: 3000
  db:
    image: mongo:5.0
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - school-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: school

  kafka-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    expose:
      - 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on: 
      - kafka-zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: kafka-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    expose:
      - 29092
  
  kafka-ui:
    image: provectuslabs/kafka-ui
    depends_on:
      - kafka
      - kafka-zookeeper
    ports:
      - 9000:8080
    environment:
      # - KAFKA_CLUSTERS_0_NAME=local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: kafka-zookeeper:2181
      
volumes:
  school-db: